name: CI

on: [push]

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn
      - name: Run Tests
        working-directory: ./frontend
        run: yarn test

  backend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./backend
        run: yarn
      - name: Run Tests
        working-directory: ./backend
        run: yarn test
